name: journal_linker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  shimmer: ^3.0.0
  image_picker: ^1.0.1
  validators: ^3.0.0
  url_launcher: ^6.1.12
  flutter_svg: ^2.0.7
  introduction_screen: ^3.1.3
  cached_network_image: ^3.2.3
  auto_route: ^6.4.0
  pin_code_fields: ^8.0.1
  images_picker: ^1.2.11
  permission_handler: ^10.4.3
  animation_wrappers: ^3.0.0
  clipboard: ^0.1.3
  dropdown_button2: ^2.3.8
  dropdown_search: ^0.6.1
  currency_text_input_formatter: ^2.0.1
  curved_navigation_bar: ^1.0.3
  loading_indicator: ^3.1.1
  pull_to_refresh: ^2.0.0

  # State Management
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.5
  # Connect Server
  http: ^1.1.0
  dio: ^5.3.0
  envify: ^2.0.3
  connectivity_plus: ^5.0.1
  json_annotation: ^4.8.1

  # run this command to generate: flutter packages pub run build_runner build
  injectable: ^2.1.2
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html: ^0.14.6
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0
  simple_circular_progress_bar: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.9.0
  injectable_generator: ^2.1.6
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  auto_route_generator: ^6.2.0
  retrofit_generator: ^7.0.1
  json_serializable: ^6.6.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/gif/
    - assets/fonts/
flutter_native_splash:
  android: true
  ios: true
  web: true
  background_image: 'assets/images/SplashScreen.jpg'
